# Generated by Django 6.0.2 on 2026-03-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=30, unique=True, verbose_name='Направление курсов')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_course', models.CharField(max_length=30, unique=True, verbose_name='Название курса')),
                ('description_course', models.CharField(max_length=300, verbose_name='Описание курса')),
                ('date_start_course', models.DateField(verbose_name='Дата начала обучения')),
                ('price_course', models.IntegerField(verbose_name='Цена курса')),
            ],
        ),
    ]
