# Generated by Django 6.0.2 on 2026-03-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courses_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='description_course',
            field=models.CharField(max_length=150, verbose_name='Описание курса'),
        ),
    ]
