# Generated by Django 6.0.2 on 2026-03-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_courses_description_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='description_course',
            field=models.CharField(max_length=300, verbose_name='Описание курса'),
        ),
    ]
